[colors.bright]
black = "0x767676"
blue = "0x3b78ff"
cyan = "0x61d6d6"
green = "0x16c60c"
magenta = "0xb4009e"
red = "0xe74856"
white = "0xf2f2f2"
yellow = "0xf9f1a5"

[colors.normal]
black = "0x0c0c0c"
blue = "0x0037da"
cyan = "0x3a96dd"
green = "0x13a10e"
magenta = "0x881798"
red = "0xc50f1f"
white = "0xcccccc"
yellow = "0xc19c00"

[colors.primary]
background = "#000000"
foreground = "0xcccccc"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[shell]
program = "/usr/bin/zsh"

[window]
dynamic_title = true
