require 'joshuatonga.packer'
require 'joshuatonga.general'
require 'joshuatonga.mappings'
require 'joshuatonga.theme'
require 'joshuatonga.plugins.nerdtree'
require 'joshuatonga.plugins.treesitter'
require 'joshuatonga.plugins.nerdcommenter'
