[helpers]

[default]
depends = []

[default.files]
"ag/.ignore" = "~/.ignore"
alacritty = "~/.config/alacritty"
"commitizen/.cz-config" = "~/.cz-config"
"commitizen/.czrc" = "~/.czrc"
"general/.fonts" = "~/.fonts"
"general/bin" = "~/.fonts"
"general/scripts" = "~/.fonts"
"git/.gitconfig" = "~/.gitconfig"
"git/.gitconfig-global" = "~/.gitconfig-global"
"gvim/.gvimrc" = "~/.gvimrc"
i3 = "~/.config/i3"
i3blocks = "~/.config/i3blocks"
i3status = "~/.config/i3status"
lazygit = "~/.config/lazygit"
nvim = "~/.config/nvim"
paymongo = "~/.dotfiles-paymongo"
personal = "~/.dotfiles-personal"
"powerlevel10k/.p10k.zsh" = "~/p10k.sh"
s = "~/.config/s"
"tmux/.tmux-startup.sh" = "~/.tmux-startup.sh"
"tmux/.tmux.conf" = "~/.tmux.conf"
wired = "~/.config/wired"
"zsh/.zsh-config" = "~/.zsh-config"
"zsh/.zshrc" = "~/.zshrc"

[default.variables]
